# Generated by Django 5.0.6 on 2024-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=15)),
                ("surname", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=254)),
                ("login", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=255)),
                ("gender", models.IntegerField()),
                ("darktheme", models.BooleanField(default=False)),
                ("token", models.CharField(max_length=255)),
            ],
        ),
    ]
